include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    avoid_returning_null_for_future: true
    avoid_types_as_parameter_names: true
    collection_methods_unrelated_type: true
    discarded_futures: true
    empty_statements: true
    list_remove_unrelated_type: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    throw_in_finally: true
    unrelated_type_equality_checks: true
    use_key_in_widget_constructors: true
    use_build_context_synchronously: true
    valid_regexps: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_catching_errors: true
    avoid_escaping_inner_quotes: true
    avoid_final_parameters: true
    use_super_parameters: true
    require_trailing_commas: true
    await_only_futures: true
    empty_constructor_bodies: true
    file_names: true
    sort_constructors_first: true
